set_property PACKAGE_PIN P17 [get_ports hwClock]

set_property PACKAGE_PIN R1 [get_ports gamePauseSignal]

set_property PACKAGE_PIN U4 [get_ports {tennisSpeedControls[2]}]
set_property PACKAGE_PIN R15 [get_ports {tennisSpeedControls[1]}]
set_property PACKAGE_PIN R17 [get_ports {tennisSpeedControls[0]}]

set_property PACKAGE_PIN V1 [get_ports lHitSignal]
set_property PACKAGE_PIN R11 [get_ports rHitSignal]

set_property PACKAGE_PIN F6 [get_ports {tennisLeds[7]}]
set_property PACKAGE_PIN G4 [get_ports {tennisLeds[6]}]
set_property PACKAGE_PIN G3 [get_ports {tennisLeds[5]}]
set_property PACKAGE_PIN J4 [get_ports {tennisLeds[4]}]
set_property PACKAGE_PIN H4 [get_ports {tennisLeds[3]}]
set_property PACKAGE_PIN J3 [get_ports {tennisLeds[2]}]
set_property PACKAGE_PIN J2 [get_ports {tennisLeds[1]}]
set_property PACKAGE_PIN K2 [get_ports {tennisLeds[0]}]

set_property PACKAGE_PIN K1 [get_ports lServeLed]
set_property PACKAGE_PIN K3 [get_ports rServeLed]

set_property PACKAGE_PIN G2 [get_ports {digitSelectors[7]}]
set_property PACKAGE_PIN C2 [get_ports {digitSelectors[6]}]
set_property PACKAGE_PIN C1 [get_ports {digitSelectors[5]}]
set_property PACKAGE_PIN H1 [get_ports {digitSelectors[4]}]
set_property PACKAGE_PIN G1 [get_ports {digitSelectors[3]}]
set_property PACKAGE_PIN F1 [get_ports {digitSelectors[2]}]
set_property PACKAGE_PIN E1 [get_ports {digitSelectors[1]}]
set_property PACKAGE_PIN G6 [get_ports {digitSelectors[0]}]

set_property PACKAGE_PIN D5 [get_ports {digitSegmentsL[7]}]
set_property PACKAGE_PIN B2 [get_ports {digitSegmentsL[6]}]
set_property PACKAGE_PIN B3 [get_ports {digitSegmentsL[5]}]
set_property PACKAGE_PIN A1 [get_ports {digitSegmentsL[4]}]
set_property PACKAGE_PIN B1 [get_ports {digitSegmentsL[3]}]
set_property PACKAGE_PIN A3 [get_ports {digitSegmentsL[2]}]
set_property PACKAGE_PIN A4 [get_ports {digitSegmentsL[1]}]
set_property PACKAGE_PIN B4 [get_ports {digitSegmentsL[0]}]

set_property PACKAGE_PIN H2 [get_ports {digitSegmentsR[7]}]
set_property PACKAGE_PIN D2 [get_ports {digitSegmentsR[6]}]
set_property PACKAGE_PIN E2 [get_ports {digitSegmentsR[5]}]
set_property PACKAGE_PIN F3 [get_ports {digitSegmentsR[4]}]
set_property PACKAGE_PIN F4 [get_ports {digitSegmentsR[3]}]
set_property PACKAGE_PIN D3 [get_ports {digitSegmentsR[2]}]
set_property PACKAGE_PIN E3 [get_ports {digitSegmentsR[1]}]
set_property PACKAGE_PIN D4 [get_ports {digitSegmentsR[0]}]



set_property IOSTANDARD LVCMOS33 [get_ports hwClock]

set_property IOSTANDARD LVCMOS33 [get_ports gamePauseSignal]

set_property IOSTANDARD LVCMOS33 [get_ports {tennisSpeedControls[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tennisSpeedControls[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tennisSpeedControls[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports lHitSignal]
set_property IOSTANDARD LVCMOS33 [get_ports rHitSignal]

set_property IOSTANDARD LVCMOS33 [get_ports {tennisLeds[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tennisLeds[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tennisLeds[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tennisLeds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tennisLeds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tennisLeds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tennisLeds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tennisLeds[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports lServeLed]
set_property IOSTANDARD LVCMOS33 [get_ports rServeLed]

set_property IOSTANDARD LVCMOS33 [get_ports {digitSelectors[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSelectors[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSelectors[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSelectors[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSelectors[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSelectors[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSelectors[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSelectors[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {digitSegmentsL[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSegmentsL[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSegmentsL[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSegmentsL[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSegmentsL[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSegmentsL[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSegmentsL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSegmentsL[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {digitSegmentsR[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSegmentsR[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSegmentsR[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSegmentsR[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSegmentsR[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSegmentsR[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSegmentsR[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitSegmentsR[0]}]